print ("Programa que disseca uma variavel")
valor = (input("Digite algo: "))
print ("O tipo primitivo desse valor é",type(valor))
print ("Só tem espaços?",valor.isspace())
print ("Só tem números?",valor.isnumeric())
print ("É alfabetico?",valor.isalpha())
print ("É alfanumerico?",valor.isalnum())
print ("Está em maisculas?",valor.isupper())
print ("Está em minusculas?",valor.islower())
print (f"Está capitalizada? {valor.istitle()}")